### ISSUE TITLE
RE: HN-Vignolles and Making Things Go/Seth

### ISSUE THREAD

**Issue by silver2row** [silver2row/pyBot#1]
Hello,

Should we add more software soon? What do you want to do w/ all this software? Give a shout out when you have time.

Seth

P.S. I am learning about WSGI right now and how to produce certain things online via web pages and applications.

**Comment by HN-Vignolles** [comment]
Adding a Webserver (easier than Flask maybe?) would be good

**Comment by silver2row** [comment]
Okay. I am on it. I just do not know everything just yet. 

Updates will be on the way and soon!

Seth

**Comment by silver2row** [comment]
@HN-Vignolles , okay...I am ending this commenting stuff for now. I will add stuff soon.

Seth
